// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyfozquqfevztzhuhmyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5Zm96cXVxZmV2enR6aHVobXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDkwOTAsImV4cCI6MjA2NDI4NTA5MH0.CYxxAE-_piP-Kc13QZiAby3KrHh1VA5fTAYCB-J6vBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});